send:
#	scp $(BINDIR_R)/$(BIN) root@80.114.140.50:/home/root/esLAB/helloDSP/.
	scp armMeanshiftExec root@88.202.161.61:/home/root/esLAB/code_laurens/. #&& scp gmon.out root@88.202.161.61:/home/root/esLAB/code_laurens/.

